CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT,
    requestor_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_item PRIMARY KEY,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT                                    NOT NULL,
    is_available BOOLEAN,
    owner_id     BIGINT                                  NOT NULL
        CONSTRAINT items_users_id_fk REFERENCES users
);



CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT                                  NOT NULL
        CONSTRAINT bookings_items_id_fk REFERENCES items,
    booker_id  BIGINT                                  NOT NULL
        CONSTRAINT bookings_users_id_fk REFERENCES users,
    status     VARCHAR(512),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      TEXT,
    item_id   BIGINT                                  NOT NULL
        CONSTRAINT comments_items_id_fk REFERENCES items,
    author_id BIGINT                                  NOT NULL
        CONSTRAINT comments_users_id_fk REFERENCES users,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);
